# Example Config File

default:
  location: top_right
  x_offfset: 0
  y_offset: 0

menus:
  - name: main-menu
    x_offset: -10
    y_offset: 10
    items:
      - type: slider
        label: "Brightness"
        # Slider always goes 0-100%. Min and Max convert these values for command input and output
        # get/set_cmd_min/max can be defined seperately, or cmd_min/max will set both
        # undefined mins will be assumed 0 and maxes will be assumed 100
        cmd_max: 255
        get_cmd: "brightnessctl g"
        set_cmd: "brightnessctl set %.0f"
      - type: slider
        label: "Volume"
        cmd_max: 1.0
        get_cmd: "wpctl get-volume @DEFAULT_AUDIO_SINK@"
        set_cmd: "wpctl set-volume @DEFAULT_AUDIO_SINK@ %.2f"
      - type: button
        label: "Audio Settings"
        cmd: "pavucontrol"
      - type: button
        label: "Shut Down"
        cmd: "loginctl poweroff"
      - type: button
        label: "Reboot"
        cmd: "loginctl reboot"
